// Ids with a glyph PNG in client/public/sprites/glyphs/{mobs,classes}/.
export const MOB_GLYPHS: readonly string[] = [
  'tunnel_rat',
  'cave_bat_swarm',
  'warren_spider',
  'goblin_scrapper',
  'rubble_slime',
  'feral_miner',
  'alpha_wolf',
  'bandit_captain',
  'cave_troll',
  'the_rat_king',
  'fungal_crawler',
  'cave_lurker',
  'spore_shambler',
  'glowcap_swarm',
  'sporecap_brute',
  'mycelium_guardian',
  'mycelium_king',
  'shard_beetle',
  'prism_wisp',
  'crystal_spider',
  'resonance_stalker',
  'geode_golem',
  'facet_matriarch',
  'prismatic_colossus',
  'drowned_shambler',
  'cave_eel',
  'tide_crawler',
  'salt_wraith',
  'abyssal_angler',
  'kraken_spawn',
  'the_drowned_leviathan',
  'bone_rattler',
  'marrow_leech',
  'skull_sentinel',
  'grave_warden',
  'bone_colossus',
  'lich_remnant',
  'the_charnel_king',
  'cinder_imp',
  'magma_beetle',
  'ash_stalker',
  'lava_slime',
  'obsidian_sentinel',
  'pyroclast_wyrm',
  'the_forge_titan',
];
export const CLASS_GLYPHS: readonly string[] = [
  'vanguard',
  'shadowblade',
  'cleric',
  'artificer',
];

// Furnishing definition ids (server/src/data/furnishingData.json) mapped to their installed variant
// count. Each id with N variants has PNGs at client/public/sprites/glyphs/furnishings/<id>-0.png..<id>-(N-1).png.
export const FURNISHING_GLYPHS: Readonly<Record<string, number>> = {
  starter_rubble: 4,
  starter_bones: 5,
  starter_collapsed_cart: 3,
  starter_table: 4,
  starter_chair: 5,
  starter_barrel: 6,
  starter_rotting_shelf: 5,
  starter_locked_chest: 5,
  starter_stalagmite: 7,
  starter_mushroom_cluster: 7,
  starter_puddle: 2,
  starter_glowing_fungus: 3,
  starter_strange_fossil: 4,
  starter_crate: 5,
  starter_cobwebs: 1,
  starter_shrine: 4,
  starter_old_skeleton: 4,
  starter_pillar: 4,
  starter_throne: 5,
  starter_brazier: 5,
  starter_altar: 4,
  starter_weapon_rack: 3,
};
