// Ids with a glyph PNG in client/public/sprites/glyphs/{mobs,classes}/.
export const MOB_GLYPHS: readonly string[] = [
  'tunnel_rat',
  'cave_bat_swarm',
  'warren_spider',
  'goblin_scrapper',
  'rubble_slime',
  'feral_miner',
  'alpha_wolf',
  'bandit_captain',
  'cave_troll',
  'the_rat_king',
  'fungal_crawler',
  'cave_lurker',
  'spore_shambler',
  'glowcap_swarm',
  'sporecap_brute',
  'mycelium_guardian',
  'mycelium_king',
  'shard_beetle',
  'prism_wisp',
  'crystal_spider',
  'resonance_stalker',
  'geode_golem',
  'facet_matriarch',
  'prismatic_colossus',
  'drowned_shambler',
  'cave_eel',
  'tide_crawler',
  'salt_wraith',
  'abyssal_angler',
  'kraken_spawn',
  'the_drowned_leviathan',
  'bone_rattler',
  'marrow_leech',
  'skull_sentinel',
  'grave_warden',
  'bone_colossus',
  'lich_remnant',
  'the_charnel_king',
  'cinder_imp',
  'magma_beetle',
  'ash_stalker',
  'lava_slime',
  'obsidian_sentinel',
  'pyroclast_wyrm',
  'the_forge_titan',
];
export const CLASS_GLYPHS: readonly string[] = [
  'vanguard',
  'shadowblade',
  'cleric',
  'artificer',
];

// Furnishing definition ids (server/src/data/furnishingData.json) with a glyph PNG in client/public/sprites/glyphs/furnishings/.
export const FURNISHING_GLYPHS: readonly string[] = [];
