// Mob template ids with a close-up PNG in client/public/closeups/mobs/. Written by scripts/closeups/install-mobs.mjs.
export const MOB_CLOSE_UPS: readonly string[] = [
  'alpha_wolf',
  'bandit_captain',
  'cave_bat_swarm',
  'cave_lurker',
  'cave_troll',
  'crystal_spider',
  'facet_matriarch',
  'feral_miner',
  'fungal_crawler',
  'geode_golem',
  'glowcap_swarm',
  'goblin_scrapper',
  'mycelium_guardian',
  'mycelium_king',
  'prism_wisp',
  'prismatic_colossus',
  'resonance_stalker',
  'rubble_slime',
  'shard_beetle',
  'spore_shambler',
  'sporecap_brute',
  'the_rat_king',
  'tunnel_rat',
  'warren_spider',
];
